/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SC_j } from "./SC_j";
export * as factories from "./factories";
export { SC_j__factory } from "./factories/SC_j__factory";
